site_name: Arrow Data Contract

repo_url: https://github.com/brunomurino/arrow-data-contract/

theme:
  name: material
  custom_dir: docs/_overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

extra:
  version:
    provider: mike